### PR TITLE
Exclude Unnecessary Files from Entropy Calculations

### LINKED ISSUE #85: Function that ignores files that are not needed for entropy calculation
### Existing issue check

- [X] I found no existing [issues](https://github.com/software-gardening/almanack/issues) covering this topic.

### Description

Currently we are tracking entropy of all files that exist. However files such as `poetry.lock` and `package-lock.json` should not be included in the calculation.

### Example

This could be done before the function `get_edited_files` . Possibly calling a function before then so it does not track the unnecessary files.

### Would you like to work on a solution for this?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by willdavidson05**
# Description
This PR aims to refine methods in `entropy.py` to no longer take in unnecessary files. This is particularly important with `calculate_normalized_entropy` since taking into account lock files (`poetry.lock`,` package-lock.json`) and configuration files (`pyproject.toml`, `.gitignore`) affects the overall entropy. 

I figured that it made sense to only add the filter to the entropy calculation, since other metrics(i.e. `repo_file_count`) might want to still take this into account. 

I appreciate any feedback or comments on this implementation. Thanks!

Closes #85 

## What is the nature of your change?

- [ ] Content additions or updates (adds or updates content)
- [ ] Bug fix (fixes an issue).
- [X] Enhancement (adds functionality).
- [ ] Breaking change (these changes would cause existing functionality to not work as expected).

# Checklist

Please ensure that all boxes are checked before indicating that this pull request is ready for review.

- [X] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own contributions.
- [X] I have commented my content, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to related documentation (outside of book content).
- [X] My changes generate no new warnings.
- [X] New and existing tests pass locally with my changes.
- [X] I have added tests that prove my additions are effective or that my feature works.
- [X] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Comment by willdavidson05** [comment]
I believe that my pre-commit check is failing due to the sbom.json file. I'm not sure how to fix this other than running the pre-commit CLI, so I may need some guidance to resolve this.

**Review by d33bs — COMMENTED** [review]
Thank you for submitting this Will!! As I read through the changes I wondered about questions on two fronts we might consider:
- The application of this to `get_loc_changed` made me wonder if we're treating the filtered files as "not code" and instead as "data". There are some files by which we will never be able to gather a "lines of code" count in that they're non-text (binaries, for example). Some of the files included are probably better classified as data (`.json`) while others are closer to code (`.gitignore`). I wonder if we should be specific about what type of files are being filtered to help make things more precise. That being said, I don't have a good idea about how to make this decision more broadly for others in the implementation of the `almanack`. For example, who's to say you couldn't "code" through `.json`, or that code (`.py` files, for ex.) aren't data?
- Did the author of [Predicting Faults Using the Complexity of Code Changes](https://doi.org/10.1109/ICSE.2009.5070510) do something similar which we could base these changes on? If they didn't perform this type of filtering we might consider avoiding the filter to retain the data about entropy for those files (it could be important in a way we don't yet understand). If they did perform this type of filtering we might consider making sure to follow how they did it (including files or perhaps as part of the entropy calculations).

Interested to hear your thoughts! Let me know if I can clarify at all.

**Comment by willdavidson05** [comment]
Thank you for the feedback @d33bs, you brought up some good points between data and code that I did not think about. I was trying to excluded files such as .lock and temp files that seemed unlikely to contribute meaningful entropy. For example, when we were processing multiple PubMed repos and the Almanack, there would be instances where the entropy would be extremely high, but only files like the ones here were affected. This seemed a little inaccurate, and I was thinking that their could be a fix for this, such as a filter of some sorts to possibly make our entropy measurement more accurate(especially when looking at the entropy of a whole repo).

After going back to the paper, they did mention filtering through any files, and I definitely agree that we might be losing some insights with this. 

Thinking about this more, maybe it would make sense to not have a filter, and continue to look at all the data as entropic? Or maybe we could have a filter thats optional and allows users to configure as needed? 

Please let me know what your thoughts are! I think its hard to create an ambiguous filter that doesn't lose any information, but maybe a way to maximize our entropy calculation.

**Comment by d33bs** [comment]
Apologies for my delay in replying here @willdavidson05:

> Thinking about this more, maybe it would make sense to not have a filter, and continue to look at all the data as entropic?

I think this sounds like the best for now. Since we don't know whether or how this information could be important I think leaving it as-is is a good idea. From a software perspective, it's a best practice is to avoid the preemptive temptation to pre-optimize before we understand what the firm requirements might be. This is commonly referred to through [YAGNI, or "you ain't gonna need it"](https://martinfowler.com/bliki/Yagni.html), which stipulates that we should only build things when directly required. In practice this can sometimes feel like we're being a bit naïve but it tends to save us time and frustration; I see it as letting the work or stakeholders/customers guide the evolution of the product, making for a multi-perspectival growth.

Thanks just the same for your efforts here - it might not have been clear if you hadn't create the PR and subsequent discussion.

**Pull request closed without merging**
